server:
  port: 9100

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/lzc199/config-cloud
          username: 454320130@qq.com
          password:
      profile: dev

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

